onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - msgpackr-extract
  - prisma
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  better-sqlite3: true
  esbuild: true
  prisma: true
